### ISSUE TITLE
Error adding taxa 

### ISSUE THREAD

**Issue by lsaravia** [mangal-interactions/rmangal-v1#14]
I first create a user with the http://mangal.uqar.ca/dashboard/ and then try to add data:

```
api <- mangalapi(usr="lsar***", key="*****")

sp1 <- list(name = "Yoldia eightsi")
sp1 <- addTaxa(api, sp1)

$error
[1] "The 'owner' field was given data that was not a URI, not a dictionary-alike and does not have a 'pk' attribute: [u'/api/v1/user/11/']."

Error en mangalPost(api, "taxa", data) : client error: (400) Bad Request
```

**Comment by tpoisot** [comment]
It's because `jsonlite` has the (very annoying IMHO) property of putting everything into arrays. I'm fixing the code where it's needed.

**Comment by tpoisot** [comment]
OK, you can re-try (with another taxa, though, I added this one for testing)

Thanks for signalling bugs, by the way!
