### ISSUE TITLE
Field owner can't be used but with listTaxa()

### ISSUE THREAD

**Issue by lsaravia** [mangal-interactions/rmangal-v1#20]
I would like to know which species I've uploaded, but I can only access the field "owner" using the function listTaxa(), and not using mangalSearch(), this would be inconvenient if thousands of taxa have been uploaded.

**Comment by tpoisot** [comment]
`mangalSearch` will be removed in the next version (see the branch `dev`), and all searchs will be done trough the `list***` functions. The issue with using `owner` for taxa is that when a taxa is edited, the value of the field can change. Example, if I edit one of your taxa, I will become the owner (it allows to find the last person that modified an object).

**Comment by lsaravia** [comment]
I thought only the owner could edit the data,  in the case of taxa it may be reasonable that other people could edit it but the ones with status="trophic species", "morphospecies" are user specific so they shouldn't be modified by other users.

**Comment by tpoisot** [comment]
Any object can be edited by its user, and by the curators, for example to fill-in missing taxonomic IDs. I'll think about not changing the `owner` field.

The point is that when the volume of data will grow, more than one network will share the same taxa, so taxa ownership will become less relevant. You can e.g. add a dataset using some taxa you uploaded, and some taxa that are already present in the database.

**Comment by tpoisot** [comment]
OK, so I gave that one some more thought.

I've updated the package so that the value of the field `owner` is maintained when an object is patched. You can filter your taxa with:

```  R
listTaxa(api, filters='owner__username=lsaravia')
```

Note  that some of the taxa you uploaded won't be retrieved this way since I patched them during the tests.
