### ISSUE TITLE
Using the toIgraph function gives duplicated vertex name

### ISSUE THREAD

**Issue by lsaravia** [mangal-interactions/rmangal-v1#22]
```
  net_obj$id

  [1] "18"

  g <- toIgraph(api, net_obj$id)

  Error en graph.data.frame(edge_list, vertices = vertices_df) : 
  Duplicate vertex names

  Además: Mensajes de aviso perdidos
  In graph.data.frame(edge_list, vertices = vertices_df) :
  In `vertices[,1]' `NA' elements were replaced with string "NA"
```

**Comment by tpoisot** [comment]
If you look at the API resource for this one (network 18), you'll see that it involves interactions `128` and `129`, which are between the same taxa (`41` and `45`). Whether or not this is intended I can't tell, but probably iGraph chokes on having two edges between the same nodes. The easy option is for you you to patch the resource, and I'll write a fix to make sure that either networks are imported as multigraphs, or the data frames are cleaned before converting to igraph.

**Comment by lsaravia** [comment]
But the interaction 129 is not in the list of interactions, I did not added.

net_obj<-getNetwork(api,18)
net_obj$interactions

On Thu, Jun 19, 2014 at 6:10 PM, Timothée Poisot notifications@github.com
wrote:

> If you look at the API resource for this one (network 18), you'll see that
> it involves interactions 128 and 129, which are between the same taxa (41
> and 45). Whether or not this is intended I can't tell, but probably
> iGraph chokes on having two edges between the same nodes. The easy option
> is for you you to patch the resource, and I'll write a fix to make sure
> that either networks are imported as multigraphs, or the data frames are
> cleaned before converting to igraph.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mangal-wg/rmangal/issues/22#issuecomment-46617142.

## 

Dr. Leonardo A. Saravia
Área Biología y Bioinformática
Instituto de Ciencias
Universidad Nacional de General Sarmiento
J.M. Gutierrez 1159 (1613) Los Polvorines
Buenos Aires Argentina
Tel: 54 11 4469-7533
http://lsaravia.github.io/

**Comment by tpoisot** [comment]
Can you try with the version on the `hotfix-igraph` branch? I think you can install it with

```
install_github('mangal-wg/rmangal', branch='hotfix-igraph')
```

This _should_ solve the problem. My connection is very bad, so I can't run to many tests.

**Comment by lsaravia** [comment]
Ok, now it's working, but the problem is that there is that "hidden"
repeated interaction, if I check I can't see the repetitions but it is
there as you mentioned because it is in the igraph object.

> net_obj<-getNetwork(api,18)
> net_obj$interactions
> [1] "125" "126" "127" "128" "130" "131" "132" "133" "134" "135" "136"

On Thu, Jun 19, 2014 at 10:05 PM, Timothée Poisot notifications@github.com
wrote:

> Can you try with the version on the hotfix-igraph branch? I think you can
> install it with
> 
> install_github('mangal-wg/rmangal', branch='hotfix-igraph')
> 
> This _should_ solve the problem. My connection is very bad, so I can't
> run to many tests.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mangal-wg/rmangal/issues/22#issuecomment-46635252.

## 

Dr. Leonardo A. Saravia
Área Biología y Bioinformática
Instituto de Ciencias
Universidad Nacional de General Sarmiento
J.M. Gutierrez 1159 (1613) Los Polvorines
Buenos Aires Argentina
Tel: 54 11 4469-7533
http://lsaravia.github.io/

**Comment by tpoisot** [comment]
What is the output of getInteraction(API, 129)?

Le vendredi 20 juin 2014, lsaravia notifications@github.com a écrit :

> Ok, now it's working, but the problem is that there is that "hidden"
> repeated interaction, if I check I can't see the repetitions but it is
> there as you mentioned because it is in the igraph object.
> 
> > net_obj<-getNetwork(api,18)
> > net_obj$interactions
> > [1] "125" "126" "127" "128" "130" "131" "132" "133" "134" "135" "136"
> 
> On Thu, Jun 19, 2014 at 10:05 PM, Timothée Poisot <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Can you try with the version on the hotfix-igraph branch? I think you
> > can
> > install it with
> > 
> > install_github('mangal-wg/rmangal', branch='hotfix-igraph')
> > 
> > This _should_ solve the problem. My connection is very bad, so I can't
> > run to many tests.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mangal-wg/rmangal/issues/22#issuecomment-46635252.
> 
> ## 
> 
> Dr. Leonardo A. Saravia
> Área Biología y Bioinformática
> Instituto de Ciencias
> Universidad Nacional de General Sarmiento
> J.M. Gutierrez 1159 (1613) Los Polvorines
> Buenos Aires Argentina
> Tel: 54 11 4469-7533
> http://lsaravia.github.io/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mangal-wg/rmangal/issues/22#issuecomment-46661212.

## 

Sent from my iPhone.

**Comment by lsaravia** [comment]
> getInteraction(api, 129)
> $description
> NULL

$id
[1] "129"

$item_from
NULL

$item_to
NULL

$link_type
[1] ""

$obs_type
[1] ""

$owner
[1] "lsaravia"

$pop_from
NULL

$pop_to
NULL

$public
[1] TRUE

$stage_from
[1] "all"

$stage_to
[1] "all"

$strength_f
NULL

$strength_t
NULL

$taxa_from
[1] "45"

$taxa_to
[1] "41"

$units_f
NULL

$units_t
NULL

**Comment by lsaravia** [comment]
There was another duplicated interaction, I patched the network and
toIgrahp works well.

Thanks!

On Sat, Jun 21, 2014 at 6:58 AM, Leonardo Saravia lsaravia@ungs.edu.ar wrote:

> > getInteraction(api, 129)
> > $description
> > NULL
> 
> $id
> [1] "129"
> 
> $item_from
> NULL
> 
> $item_to
> NULL
> 
> $link_type
> [1] ""
> 
> $obs_type
> [1] ""
> 
> $owner
> [1] "lsaravia"
> 
> $pop_from
> NULL
> 
> $pop_to
> NULL
> 
> $public
> [1] TRUE
> 
> $stage_from
> [1] "all"
> 
> $stage_to
> [1] "all"
> 
> $strength_f
> NULL
> 
> $strength_t
> NULL
> 
> $taxa_from
> [1] "45"
> 
> $taxa_to
> [1] "41"
> 
> $units_f
> NULL
> 
> $units_t
> NULL

## 

Dr. Leonardo A. Saravia
Área Biología y Bioinformática
Instituto de Ciencias
Universidad Nacional de General Sarmiento
J.M. Gutierrez 1159 (1613) Los Polvorines
Buenos Aires Argentina
Tel: 54 11 4469-7533
http://lsaravia.github.io/
