### ISSUE TITLE
Add a list of references (doi) to the interaction object

### ISSUE THREAD

**Issue by lsaravia** [mangal-interactions/rmangal-v1#23]
There could be several references that document the interaction, thus a list of doi should be linked to interactions.

**Comment by tpoisot** [comment]
You are entirely right. We stumbled upon a new use case a few days ago, and we will most likely tweak the reference system a bit. This is planned, but may take a few weeks to be here (basically we are waiting on the first round of reviews to release a bunch of changes).

**Comment by tpoisot** [comment]
Also please use this repo: https://github.com/mangal-wg/mangal-schemes for comments on the data structure. This is not about the r package.

**Comment by tpoisot** [comment]
Done in the upcoming API release (along with much other goodness!)
