### ISSUE TITLE
possibility to retrieve the metaweb of a dataset

### ISSUE THREAD

**Issue by ibartomeus** [mangal-interactions/rmangal-v1#9]
I would also think can be useful to retrieve the metaweb (all webs pooled) of a dataset directly, rather than retrieve all webs independently. Not a priority.

**Comment by tpoisot** [comment]
We are working on another package focused entirely on metaweb reconstruction. The function to pull a metaweb from a dataset will be in the other one. I'll keep you updated when we have a version ready to be released.
